// AUTO-GENERATED by scripts/contract_sync.py — DO NOT EDIT BY HAND.
// Source of truth: backend/api/schemas/contract.py (pydantic, ADR 0003).
// Regenerate:  python3 scripts/contract_sync.py
// Verify (CI): python3 scripts/contract_sync.py --check
import { z } from "zod";

export const NodeClassificationSchema = z.enum(["king", "wall", "gatekeeper", "significant", "normal"]);
export type NodeClassification = z.infer<typeof NodeClassificationSchema>;
export const GammaNodeSchema = z.object({
  strike: z.number(),
  expiry_date: z.string(),
  net_gex: z.number(),
  value: z.number(),
  classification: z.lazy(() => NodeClassificationSchema),
}).strict();
export type GammaNode = z.infer<typeof GammaNodeSchema>;

export const HealthResponseSchema = z.object({
  status: z.literal("ok"),
  version: z.string(),
}).strict();
export type HealthResponse = z.infer<typeof HealthResponseSchema>;

export const ReadyCheckSchema = z.object({
  name: z.string(),
  ok: z.boolean(),
  detail: z.string().nullable().optional(),
}).strict();
export type ReadyCheck = z.infer<typeof ReadyCheckSchema>;

export const ReadyResponseSchema = z.object({
  status: z.enum(["ready", "degraded"]),
  checks: z.array(z.lazy(() => ReadyCheckSchema)),
  last_payload_age_s: z.number().nullable().optional(),
}).strict();
export type ReadyResponse = z.infer<typeof ReadyResponseSchema>;
