#!/usr/bin/env python3
"""contract_sync.py — Zod<->pydantic single-contract generator/checker.

One contract (ADR 0003 decision 4): the pydantic models in
`backend/api/schemas/contract.py`. This script generates the frontend Zod
mirror from their JSON Schema into `frontend/src/lib/contract/contract.ts`;
`--check` (CI job `contract-sync`) fails when the committed file drifts.

Supported JSON-Schema subset (anything else fails loudly — never silently
generates a wrong schema):
  const / enum(str) · string · number · integer · boolean · null ·
  array(items) · object(properties, required, additionalProperties:false) ·
  $ref to #/$defs/<Name> · anyOf with exactly one `null` branch (nullable)

Usage:
  python3 scripts/contract_sync.py            # regenerate contract.ts
  python3 scripts/contract_sync.py --check    # exit 1 on drift (CI)

Exit codes: 0 ok, 1 drift/unsupported schema, 2 import/usage error.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(REPO, "frontend", "src", "lib", "contract", "contract.ts")

HEADER = """\
// AUTO-GENERATED by scripts/contract_sync.py — DO NOT EDIT BY HAND.
// Source of truth: backend/api/schemas/contract.py (pydantic, ADR 0003).
// Regenerate:  python3 scripts/contract_sync.py
// Verify (CI): python3 scripts/contract_sync.py --check
import { z } from "zod";
"""


class ContractSyncError(Exception):
    """Unsupported schema shape — fail loud, never guess."""


def _lit(value) -> str:
    return json.dumps(value)


def render(schema: dict, defs: dict, name: str) -> str:
    """Render one JSON-Schema node as a zod expression string."""
    if not isinstance(schema, dict):
        raise ContractSyncError(f"{name}: unsupported schema node {schema!r}")

    if "$ref" in schema:
        ref = schema["$ref"]
        if not ref.startswith("#/$defs/"):
            raise ContractSyncError(f"{name}: unsupported $ref {ref!r}")
        target = ref[len("#/$defs/"):]
        if target not in defs:
            raise ContractSyncError(f"{name}: unresolved $ref {ref!r}")
        return f"z.lazy(() => {target}Schema)"

    if "allOf" in schema:  # pydantic wraps titled refs in allOf
        if len(schema["allOf"]) == 1 and set(schema) <= {"allOf", "title", "description"}:
            return render(schema["allOf"][0], defs, name)
        raise ContractSyncError(f"{name}: unsupported allOf {schema!r}")

    if "anyOf" in schema:
        branches = schema["anyOf"]
        non_null = [b for b in branches if b != {"type": "null"}]
        if len(non_null) == 1 and len(branches) == 2:
            return f"{render(non_null[0], defs, name)}.nullable()"
        raise ContractSyncError(f"{name}: unsupported anyOf {schema!r}")

    if "const" in schema:
        return f"z.literal({_lit(schema['const'])})"

    if "enum" in schema:
        values = schema["enum"]
        if not all(isinstance(v, str) for v in values):
            raise ContractSyncError(f"{name}: only string enums supported, got {values!r}")
        return f"z.enum([{', '.join(_lit(v) for v in values)}])"

    typ = schema.get("type")
    if typ == "string":
        return "z.string()"
    if typ == "number":
        return "z.number()"
    if typ == "integer":
        return "z.number().int()"
    if typ == "boolean":
        return "z.boolean()"
    if typ == "null":
        return "z.null()"
    if typ == "array":
        if "items" not in schema:
            raise ContractSyncError(f"{name}: array without items")
        return f"z.array({render(schema['items'], defs, name + '.items')})"
    if typ == "object" or "properties" in schema:
        props = schema.get("properties", {})
        required = set(schema.get("required", []))
        if schema.get("additionalProperties") not in (False, None):
            raise ContractSyncError(f"{name}: additionalProperties must be false/absent")
        strict = ".strict()" if schema.get("additionalProperties") is False else ""
        fields = []
        for key, sub in props.items():
            expr = render(sub, defs, f"{name}.{key}")
            if key not in required:
                expr += ".optional()"
            fields.append(f"  {key}: {expr},")
        body = "\n".join(fields)
        return f"z.object({{\n{body}\n}}){strict}"

    raise ContractSyncError(f"{name}: unsupported schema {schema!r}")


def generate() -> str:
    """Build contract.ts content from the pydantic contract module."""
    if REPO not in sys.path:
        sys.path.insert(0, REPO)
    try:
        from pydantic import BaseModel

        from backend.api.schemas import contract as contract_module
    except ImportError as exc:  # pragma: no cover - env problem
        raise SystemExit(f"contract_sync: import failed ({exc}) — pip install -e '.[dev]'")

    models: list[tuple[str, type]] = []
    for attr_name, obj in vars(contract_module).items():
        if (
            isinstance(obj, type)
            and issubclass(obj, BaseModel)
            and obj.__module__ == contract_module.__name__
            and obj is not BaseModel
            # shared base class, not a contract model
            and obj is not getattr(contract_module, "ContractModel", None)
        ):
            models.append((attr_name, obj))
    models.sort(key=lambda kv: kv[0])

    out = [HEADER]
    emitted: dict[str, str] = {}

    def _emit(name: str, rendered: str, kind: str) -> None:
        if name in emitted:
            if emitted[name] != rendered:
                raise ContractSyncError(f"conflicting schema for {kind} {name!r}")
            return
        emitted[name] = rendered
        out.append(f"export const {name}Schema = {rendered};")
        out.append(f"export type {name} = z.infer<typeof {name}Schema>;")

    for model_name, model in models:
        schema = model.model_json_schema()
        defs = schema.pop("$defs", {})
        for def_name, def_schema in defs.items():
            _emit(def_name, render(def_schema, defs, def_name), "$defs")
        _emit(model_name, render(schema, defs, model_name), "model")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Zod<->pydantic contract sync")
    ap.add_argument("--check", action="store_true",
                    help="verify committed contract.ts matches generator output")
    ap.add_argument("--target", default=TARGET,
                    help="output path (default frontend/src/lib/contract/contract.ts)")
    args = ap.parse_args(argv)

    try:
        rendered = generate()
    except ContractSyncError as exc:
        print(f"contract_sync: ERROR {exc}", file=sys.stderr)
        return 1

    if args.check:
        try:
            with open(args.target, encoding="utf-8") as fh:
                committed = fh.read()
        except OSError as exc:
            print(f"contract_sync: cannot read {args.target}: {exc}", file=sys.stderr)
            return 1
        if committed != rendered:
            print(f"contract_sync: DRIFT — {args.target} is stale.", file=sys.stderr)
            print("contract_sync: run scripts/contract_sync.py and commit.", file=sys.stderr)
            return 1
        print(f"contract_sync: OK — {args.target} in sync with backend/api/schemas/contract.py")
        return 0

    os.makedirs(os.path.dirname(args.target), exist_ok=True)
    with open(args.target, "w", encoding="utf-8") as fh:
        fh.write(rendered)
    print(f"contract_sync: wrote {args.target}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
